import { observations, ssdQuestions, validateObservation } from '../content/ssd.mjs';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function ssdSection() {
  observations.forEach(validateObservation);
  return `<section class="section" id="ssd-details">
    <p class="eyebrow">SSD · beyond the balance</p><h2>Plan the collection.<br>Then plan the darshan.</h2>
    <nav class="chips" aria-label="SSD details"><a href="#ssd-reports">Ground reports</a><a href="#ssd-waits">Waiting times</a><a href="#ssd-questions">Before you travel</a></nav>
    <section class="section" id="ssd-reports"><h3>Reviewed ground reports</h3><p>Official figures appear above. Ground reports describe a particular counter and time; they do not replace the official balance.</p>
    ${observations.length ? observations.map(r=>`<article class="counter-card"><p class="eyebrow">Community report · historical observation</p><h3>${esc(r.counter)}</h3><p>${esc(r.summary)}</p><p>Collection date: ${esc(r.issuanceDate)} · Darshan date: ${esc(r.darshanDate)}</p><p>Observed: ${esc(r.observedAt)} · Reported: ${esc(r.reportedAt)}</p><p>Reviewed: ${esc(r.reviewedAt)}. This is not current availability.</p></article>`).join('') : '<p class="empty-state">No verified SSD ground reports have been published. Counter opening, queue length and issuance completion are not reported.</p>'}
    <div class="counter-grid">${['Srinivasam','Vishnu Nivasam','Bhudevi Complex'].map(name=>`<article class="counter-card"><h3>${name}</h3><p>Current SSD issuance: <strong>Not reported</strong></p><p>Token collection queue: <strong>Not reported</strong></p><p>Observed at: —</p><p>Confirm whether this location is issuing SSD tokens before travelling.</p></article>`).join('')}</div></section>
    <section class="section" id="ssd-waits"><h3>Two queues, two different waits</h3><div class="token-grid"><article><h3>Collecting your token</h3><p>Time spent at the issuance counter before receiving an SSD token.</p><strong>Current estimate: Not reported</strong></article><article><h3>After reporting for darshan</h3><p>Time from entering at your assigned reporting point until completing darshan.</p><strong>Current SSD estimate: Not reported</strong></article></div><p class="quiet">A tokenless Sarva Darshan wait or a combined SSD/DD estimate is not used as an SSD measurement.</p></section>
    <section class="section"><h3>Issuance timeline</h3><dl class="token-status-details"><div><dt>Issuance began</dt><dd>Not reported</dd></div><div><dt>Issuance completed</dt><dd>Not reported</dd></div><div><dt>Next release</dt><dd>Not announced here</dd></div></dl><p>The official balance alone cannot establish these times. No historical balance archive is available yet.</p></section>
    <section class="section" id="ssd-questions"><h3>Before you travel</h3><div class="daily-timetable">${ssdQuestions.map(([question,answer])=>`<details><summary>${esc(question)}</summary><p>${esc(answer)}</p></details>`).join('')}</div><p class="quiet">Guidance reviewed 11 September 2026. Your token and current TTD instructions take precedence.</p></section>
  </section>`;
}
